<a href="https://colab.research.google.com/github/Jayavathsan/TensorFlow/blob/main/convolution%20with%20output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
matrix1 = [1,1,1,1,1]
filter = [1,1,1]
padding = 0
stride = 1
result =

padding value n will be added as rows and columns to the matrix1 (i,j)

filter(i1, j1) will be a matrix which will be multiplied with the same sized sub matrix of the matrix 1 (i,j) which is matrix1(i1, j1)

then stride will be applied row wise first matrix1(i1+stride, j1)

looped till it reaches the end of the columns in the row including the padding value

then looped for the rows going down for completing all the rows till end including the padded value

In [126]:
import numpy as np
from numpy import random

In [127]:
matrix1 = random.randint(10, size=(6, 6))

In [128]:
print(matrix1)

[[2 0 1 3 2 2]
 [5 1 2 5 6 5]
 [8 0 5 5 8 8]
 [7 0 5 0 4 6]
 [1 7 5 5 5 7]
 [2 4 9 9 5 9]]


In [129]:
filter = random.randint(2, size=(3, 3))

In [130]:
print(filter)

[[1 1 0]
 [1 1 0]
 [0 0 1]]


In [131]:
matrix1 = np.pad(matrix1, pad_width=1, mode='constant', constant_values=0)

In [132]:
print(matrix1)

[[0 0 0 0 0 0 0 0]
 [0 2 0 1 3 2 2 0]
 [0 5 1 2 5 6 5 0]
 [0 8 0 5 5 8 8 0]
 [0 7 0 5 0 4 6 0]
 [0 1 7 5 5 5 7 0]
 [0 2 4 9 9 5 9 0]
 [0 0 0 0 0 0 0 0]]


In [133]:
resultMatrix = np.zeros((5,5))
print(resultMatrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [134]:
stride = 1

In [135]:
print(matrix1)

[[0 0 0 0 0 0 0 0]
 [0 2 0 1 3 2 2 0]
 [0 5 1 2 5 6 5 0]
 [0 8 0 5 5 8 8 0]
 [0 7 0 5 0 4 6 0]
 [0 1 7 5 5 5 7 0]
 [0 2 4 9 9 5 9 0]
 [0 0 0 0 0 0 0 0]]


In [136]:
submatrix = np.zeros((3,3))

In [137]:
print(submatrix.shape)
print(submatrix)

(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
submatrix = matrix1[:3,:3]
print(submatrix)
print(submatrix.shape)

[[0 0 0]
 [0 2 0]
 [0 5 1]]
(3, 3)


In [143]:
num1 = 0
num2 = 5

In [140]:
len1 = []
len2 = []
for i1 in range(0, 3):
  submatrix = matrix1[:3, :3]

print(submatrix.shape)

(3, 3)


In [158]:
result = np.zeros((5,5))
print(result)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [155]:
for i in range(0,num1):
    for j in range(0,num2):
        submatrix = matrix1[i:i+3, j:j+3]
        result[i][j] = np.sum(submatrix * filter[:, :])

In [156]:
print(result)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [148]:
matrix2 = [[4, 9, 2, 5, 8, 3],
    [5, 6, 2, 4, 0, 3],
    [2, 4, 5, 4, 5, 2],
    [5, 6, 5, 4, 7, 8],
    [5, 7, 7, 9, 2, 1],
    [5, 8, 5, 3, 8, 4]]

matrix2 = np.array(matrix2)

filter2 = [[1,0,-1],
           [1,0,-1],
           [1,0,-1]]

filter2 = np.array(filter2)

In [149]:
result2 = np.zeros((4,4))
print(result2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [150]:
submatrix2 = np.zeros((3,3))
print(submatrix2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


i totally didnt add the padding into my calculations! thank you for the heads up

In [160]:
for i in range(0, 4):
    for j in range(0, 4):
        submatrix2 = matrix2[i:i+3, j:j+3]
        result2[i][j] = np.sum(submatrix2 * filter2)

print(result2)

[[ 2.  6. -4.  5.]
 [ 0.  4.  0. -1.]
 [-5.  0.  3.  6.]
 [-2.  5.  0.  3.]]


function for nxnxn matrix with function and dynamic values


In [164]:
rows = 6
columns = 6
channels = 3
filterRows = 3
filterColumns = 3
padding = 0
stride = 1

def convolution():
    givenSize = np.random.randint(0, 10, size=(rows, columns, channels))
    filterSize = np.random.randint(-2, 3, size=(filterRows, filterColumns, channels))
    paddedIn = np.pad(givenSize, pad_width=((padding, padding), (padding, padding), (0, 0)), mode='constant', constant_values=0)
    rows_padded, columns_padded, _ = paddedIn.shape
    resultRows = (rows_padded - filterRows) // stride + 1
    resultColumns = (columns_padded - filterColumns) // stride + 1
    result3 = np.zeros((resultRows, resultColumns))

    for i in range(0, resultRows):
        for j in range(0, resultColumns):
            totalSum = 0
            for i1 in range(channels):
                startRow = i * stride
                startColumn = j * stride
                givenShape = paddedIn[startRow:startRow + filterRows, startColumn:startColumn + filterColumns, i1]
                totalSum += np.sum(givenShape * filterSize[:, :, i1])
            result3[i, j] = totalSum

    return result3, givenSize, filterSize

result3, givenSize, filterSize = convolution()
print(f"givenSize is ",givenSize)
print(f"filterSize is ",filterSize)
print(f"result3) is ",result3)


givenSize is  [[[9 2 3]
  [6 6 9]
  [6 9 9]
  [0 8 3]
  [7 1 0]
  [2 4 5]]

 [[0 1 5]
  [7 5 9]
  [1 2 9]
  [0 2 3]
  [5 2 7]
  [4 8 7]]

 [[0 0 7]
  [9 7 1]
  [7 1 8]
  [8 0 5]
  [1 3 6]
  [2 6 1]]

 [[2 8 2]
  [6 7 0]
  [2 1 7]
  [8 0 2]
  [4 7 7]
  [7 0 1]]

 [[7 3 4]
  [8 0 5]
  [7 0 2]
  [9 6 3]
  [8 7 2]
  [8 2 1]]

 [[4 5 8]
  [0 7 9]
  [2 2 8]
  [2 7 4]
  [9 0 1]
  [1 3 2]]]
filterSize is  [[[-2 -2  1]
  [ 1  1 -1]
  [ 0  2  1]]

 [[-1  0 -1]
  [-1 -1 -1]
  [ 1  1 -1]]

 [[-1 -1  0]
  [ 1  1 -2]
  [ 0  0 -2]]]
result3) is  [[-23. -53. -51. -22.]
 [-16. -65. -30.  -7.]
 [ -5. -47. -10. -28.]
 [-51. -65.   9. -35.]]


filter of 3x3x2 for an input of 6x6x3 is possible by having strides over the third dimension but i dont know how what good it would do or if it would perform well but possible because if moving the filter in y axis is possible then moving it in z axis would also be possible. I am sorry if i sound as if i am trying to prove it right but i genuinely thought about it and wanted to know if it would work, it seems to work. Thank you

In [166]:
rows = 6
columns = 6
channels = 3
filterRows = 3
filterColumns = 3
filterChannels = 2
padding = 0
stride = 1

def convolutionNew1():
    givenSize2 = np.random.randint(0, 10, size=(rows, columns, channels))
    filterSize2 = np.random.randint(-2, 3, size=(filterRows, filterColumns, filterChannels))

    paddedIn = np.pad(givenSize, pad_width=((padding, padding), (padding, padding), (0, 0)), mode='constant', constant_values=0)

    rows_padded, columns_padded, _ = paddedIn.shape
    resultRows = (rows_padded - filterRows) // stride + 1
    resultColumns = (columns_padded - filterColumns) // stride + 1

    resultMatrix = []

    for i in range(channels - 1):
        result4 = np.zeros((resultRows, resultColumns))

        for i1 in range(0, resultRows):
            for j in range(0, resultColumns):
                startRow = i * stride
                startColumn = j * stride

                # Extract regions for two consecutive channels
                givenShape1 = paddedIn[startRow:startRow + filterRows, startColumn:startColumn + filterColumns, i]
                givenShape2 = paddedIn[startRow:startRow + filterRows, startColumn:startColumn + filterColumns, i + 1]

                # Apply filter and sum results
                totalSum = np.sum(givenShape1 * filterSize[:, :, 0]) + np.sum(givenShape2 * filterSize[:, :, 1])
                result4[i, j] = totalSum

        resultMatrix.append(result4)

    resultMaps = np.stack(resultMatrix, axis=-1)
    return resultMaps, givenSize, filterSize

result4, givenSize2, filterSize2 = convolutionNew1()

print(f"givenSize is ", givenSize2)
print(f"filterSize is ", filterSize2)
print(f"result3 is ", result4)


givenSize is  [[[9 2 3]
  [6 6 9]
  [6 9 9]
  [0 8 3]
  [7 1 0]
  [2 4 5]]

 [[0 1 5]
  [7 5 9]
  [1 2 9]
  [0 2 3]
  [5 2 7]
  [4 8 7]]

 [[0 0 7]
  [9 7 1]
  [7 1 8]
  [8 0 5]
  [1 3 6]
  [2 6 1]]

 [[2 8 2]
  [6 7 0]
  [2 1 7]
  [8 0 2]
  [4 7 7]
  [7 0 1]]

 [[7 3 4]
  [8 0 5]
  [7 0 2]
  [9 6 3]
  [8 7 2]
  [8 2 1]]

 [[4 5 8]
  [0 7 9]
  [2 2 8]
  [2 7 4]
  [9 0 1]
  [1 3 2]]]
filterSize is  [[[-2 -2  1]
  [ 1  1 -1]
  [ 0  2  1]]

 [[-1  0 -1]
  [-1 -1 -1]
  [ 1  1 -1]]

 [[-1 -1  0]
  [ 1  1 -2]
  [ 0  0 -2]]]
result3 is  [[[ 15.   0.]
  [ -9.   0.]
  [-16.   0.]
  [  1.   0.]]

 [[  0.  18.]
  [  0. -21.]
  [  0.  -6.]
  [  0.  23.]]

 [[  0.   0.]
  [  0.   0.]
  [  0.   0.]
  [  0.   0.]]

 [[  0.   0.]
  [  0.   0.]
  [  0.   0.]
  [  0.   0.]]]
